/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-08-31 00:11:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import static poly.util.CmmUtil.nvl;
import java.util.List;
import java.util.ArrayList;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("static poly.util.CmmUtil.nvl");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("<title>매입/매출현황</title>\r\n");
      out.write("<!-- Favicon icon -->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\"\r\n");
      out.write("	href=\"../resource/images/favicon.png\">\r\n");
      out.write("<!-- Pignose Calender -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"../resource/plugins/pg-calendar/css/pignose.calendar.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Chartist -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"../resource/plugins/chartist/css/chartist.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"../resource/plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css\">\r\n");
      out.write("<!-- Custom Stylesheet -->\r\n");
      out.write("<link href=\"../resource/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../resource/css/saltable.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- 적용방법 3 제이 쿼리 제공 최신 버전-->\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<!-- 적용방법 2 : cdn -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!--*******************\r\n");
      out.write("        Preloader start\r\n");
      out.write("    ********************-->\r\n");
      out.write("	<div id=\"preloader\">\r\n");
      out.write("		<div class=\"loader\">\r\n");
      out.write("			<svg class=\"circular\" viewBox=\"25 25 50 50\">\r\n");
      out.write("                <circle class=\"path\" cx=\"50\" cy=\"50\" r=\"20\" fill=\"none\"\r\n");
      out.write("					stroke-width=\"3\" stroke-miterlimit=\"10\" />\r\n");
      out.write("            </svg>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--*******************\r\n");
      out.write("        Preloader end\r\n");
      out.write("    ********************-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--**********************************\r\n");
      out.write("        Main wrapper start\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("	<div id=\"main-wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!--**********************************\r\n");
      out.write("            Nav header start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("		<div class=\"nav-header\">\r\n");
      out.write("			<div class=\"brand-logo\">\r\n");
      out.write("				<a href=\"/main/index.do\"> <b class=\"logo-abbr\"><img\r\n");
      out.write("						src=\"../resource/images/logo.png\" alt=\"\"> </b> <span\r\n");
      out.write("					class=\"logo-compact\"><img\r\n");
      out.write("						src=\"../resource/images/logo-compact.png\" alt=\"\"></span> <span\r\n");
      out.write("					class=\"brand-title\"> <img\r\n");
      out.write("						src=\"../resource/images/logo-text.png\" alt=\"\">\r\n");
      out.write("				</span>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--**********************************\r\n");
      out.write("            Nav header end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("		<!--**********************************\r\n");
      out.write("            Header start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("		<div class=\"header\">\r\n");
      out.write("			<div class=\"header-content clearfix\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"nav-control\">\r\n");
      out.write("					<div class=\"hamburger\">\r\n");
      out.write("						<span class=\"toggle-icon\"><i class=\"icon-menu\"></i></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header-left\">\r\n");
      out.write("					<div class=\"input-group icons\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header-right\">\r\n");
      out.write("					<ul class=\"clearfix\">\r\n");
      out.write("\r\n");
      out.write("						<li class=\"icons dropdown\">\r\n");
      out.write("							<div class=\"user-img c-pointer position-relative\"\r\n");
      out.write("								data-toggle=\"dropdown\">\r\n");
      out.write("								<span class=\"activity active\"></span> <img\r\n");
      out.write("									src=\"../resource/images/user/1.png\" height=\"40\" width=\"40\"\r\n");
      out.write("									alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"drop-down dropdown-profile animated fadeIn dropdown-menu\">\r\n");
      out.write("								<div class=\"dropdown-content-body\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"app-profile.html\"><i class=\"icon-user\"></i>\r\n");
      out.write("												<span>Profile</span></a></li>\r\n");
      out.write("\r\n");
      out.write("										<li><a href=\"page-login.html\"><i class=\"icon-key\"></i>\r\n");
      out.write("												<span>Logout</span></a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"nk-sidebar\">\r\n");
      out.write("			<div class=\"nk-nav-scroll\">\r\n");
      out.write("				<ul class=\"metismenu\" id=\"menu\">\r\n");
      out.write("					<li><a class=\"has-arrow\" href=\"javascript:void()\"\r\n");
      out.write("						aria-expanded=\"false\"> <i class=\"icon-speedometer menu-icon\"></i><span\r\n");
      out.write("							class=\"nav-text\">가게현황</span>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul aria-expanded=\"false\">\r\n");
      out.write("							<li><a href=\"/main/currentsit.do\">가게현황관리</a></li>\r\n");
      out.write("\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class=\"mega-menu mega-menu-sm\"><a class=\"has-arrow\"\r\n");
      out.write("						href=\"javascript:void()\" aria-expanded=\"false\"> <i\r\n");
      out.write("							class=\"icon-globe-alt menu-icon\"></i><span class=\"nav-text\">매출현황</span>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul aria-expanded=\"false\">\r\n");
      out.write("							<li><a href=\"/main/daily.do\">일일매출상세보기</a></li>\r\n");
      out.write("							<li><a href=\"/main/monthly.do\">월별매출상세보기</a></li>\r\n");
      out.write("							<li><a href=\"/main/year.do\">연도별매출상세보기</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a class=\"has-arrow\" href=\"javascript:void()\"\r\n");
      out.write("						aria-expanded=\"false\"> <i class=\"icon-envelope menu-icon\"></i>\r\n");
      out.write("							<span class=\"nav-text\">급여내역</span>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul aria-expanded=\"false\">\r\n");
      out.write("							<li><a href=\"/main/manage.do\">직원급여내역</a></li>\r\n");
      out.write("\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a class=\"has-arrow\" href=\"javascript:void()\"\r\n");
      out.write("						aria-expanded=\"false\"> <i class=\"icon-screen-tablet menu-icon\"></i><span\r\n");
      out.write("							class=\"nav-text\">인원관리</span>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul aria-expanded=\"false\">\r\n");
      out.write("							<li><a href=\"/main/detail.do\">직원상세정보</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a class=\"has-arrow\" href=\"javascript:void()\"\r\n");
      out.write("						aria-expanded=\"false\"> <i class=\"icon-graph menu-icon\"></i> <span\r\n");
      out.write("							class=\"nav-text\">스케쥴</span>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul aria-expanded=\"false\">\r\n");
      out.write("							<li><a href=\"/main/calender.do\">캘린더</a></li>\r\n");
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--**********************************\r\n");
      out.write("            Sidebar end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("		<!--**********************************\r\n");
      out.write("            Content body start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("		<div class=\"content-body\">\r\n");
      out.write("			<div class=\"container-fluid mt-3\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-12\">\r\n");
      out.write("						<div class=\"card\" style=\"overflow: scorll;\">\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<div class=\"active-member\">\r\n");
      out.write("									<div class=\"table-responsive\">\r\n");
      out.write("										<div class=\"sal_table\" id=\"sal_table\">\r\n");
      out.write("											<div style=\"display: inline-flex\">\r\n");
      out.write("												<h4 style=\"float: left; margin-right: 600px;\">매출 현황</h4>\r\n");
      out.write("												<div\r\n");
      out.write("													style=\"padding: 0 1rem; flex-basis: auto; white-space: nowrap; align-self: center;\">\r\n");
      out.write("\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<input type=\"button\" value=\"추가\" id=\"addRow\">\r\n");
      out.write("											<form action=\"/main/Daily_UPDATEProc.do\">\r\n");
      out.write("												<input type=\"button\" value=\"저장\" id=\"UpdateDailyInfo\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("												<div class=\"divTable minimalistBlack\">\r\n");
      out.write("													<div class=\"divTableHeading\">\r\n");
      out.write("														<div class=\"divTableRow\">\r\n");
      out.write("															<div class=\"divTableHead\">\r\n");
      out.write("																<input type=\"checkbox\">\r\n");
      out.write("															</div>\r\n");
      out.write("															<div class=\"divTableHead\">순번</div>\r\n");
      out.write("															<div class=\"divTableHead\">날짜</div>\r\n");
      out.write("															<div class=\"divTableHead\">품목</div>\r\n");
      out.write("															<div class=\"divTableHead\">가격</div>\r\n");
      out.write("															<div class=\"divTableHead\">수량</div>\r\n");
      out.write("															<div class=\"divTableHead\">종류</div>\r\n");
      out.write("															<div class=\"divTableHead\"></div>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"divTableBody\" id=\"sal_body\" name=\"sal_body\">\r\n");
      out.write("\r\n");
      out.write("														");

														for (int i = 1; i <= 10; i++) {
														
      out.write("\r\n");
      out.write("														<div class=\"divTableRow\" id=\"sal_row\" name=\"sal_row\">\r\n");
      out.write("															<div class=\"divTableCell\" id=\"sal_ch\" name=\"sal_ch\">\r\n");
      out.write("																<input type=\"checkbox\">\r\n");
      out.write("															</div>\r\n");
      out.write("															<div class=\"divTableCell\" id=\"sal_no\" name=\"sal_no\">\r\n");
      out.write("																<span>");
      out.print(i);
      out.write("</span><input type=\"hidden\" value=");
      out.print(i);
      out.write("\r\n");
      out.write("																	class=\"makeArrayElem\">\r\n");
      out.write("															</div>\r\n");
      out.write("															<div class=\"divTableCell\" id=\"sal_date\" name=\"sal_date\">\r\n");
      out.write("																<input type=\"date\" class=\"makeArrayElem\">\r\n");
      out.write("															</div>\r\n");
      out.write("															<div class=\"divTableCell\" id=\"sal_item\" name=\"sal_item\">\r\n");
      out.write("																<input type=\"text\" class=\"makeArrayElem\">\r\n");
      out.write("															</div>\r\n");
      out.write("															<div class=\"divTableCell\" id=\"sal_price\" name=\"sal_price\">\r\n");
      out.write("																<input type=\"text\" class=\"makeArrayElem\">\r\n");
      out.write("															</div>\r\n");
      out.write("															<div class=\"divTableCell\" id=\"sal_quantity\"\r\n");
      out.write("																name=\"sal_quantity\">\r\n");
      out.write("																<input type=\"text\" class=\"makeArrayElem\">\r\n");
      out.write("															</div>\r\n");
      out.write("															<div class=\"divTableCell\" id=\"sal_kind\" name=\"sal_kind\">\r\n");
      out.write("																<select class=\"makeArrayElem\">\r\n");
      out.write("																	<option>카드</option>\r\n");
      out.write("																	<option>현금</option>\r\n");
      out.write("																	<option>배달앱</option>\r\n");
      out.write("																</select>\r\n");
      out.write("															</div>\r\n");
      out.write("															<div class=\"divTableCell\" id=\"delete\" name=\"delete\">\r\n");
      out.write("																<a href=\"#\" data-toggle=\"tooltip\" data-placement=\"top\"\r\n");
      out.write("																	title=\"\" data-original-title=\"Close\"><i\r\n");
      out.write("																	class=\"fa fa-close color-danger\" id =\"rowdelete\"></i></a>\r\n");
      out.write("															</div>\r\n");
      out.write("														</div>\r\n");
      out.write("														<input type=\"hidden\" value=\",\">\r\n");
      out.write("														");

														}
														
      out.write("\r\n");
      out.write("\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</form>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- 지각자 현황 -->\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-12\">\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<div class=\"active-member\">\r\n");
      out.write("									<div class=\"table-responsive\">\r\n");
      out.write("										<div class=\"purchase_table\">\r\n");
      out.write("											<h4>매입 현황</h4>\r\n");
      out.write("											<div class=\"divTable minimalistBlack\">\r\n");
      out.write("												<div class=\"divTableHeading\">\r\n");
      out.write("													<div class=\"divTableRow\">\r\n");
      out.write("														<div class=\"divTableHead\">\r\n");
      out.write("															<input type=\"checkbox\">\r\n");
      out.write("														</div>\r\n");
      out.write("														<div class=\"divTableHead\">순번</div>\r\n");
      out.write("														<div class=\"divTableHead\">날짜</div>\r\n");
      out.write("														<div class=\"divTableHead\">품목</div>\r\n");
      out.write("														<div class=\"divTableHead\">가격</div>\r\n");
      out.write("														<div class=\"divTableHead\">수량</div>\r\n");
      out.write("														<div class=\"divTableHead\">종류</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"divTableBody\">\r\n");
      out.write("													");

													for (int i = 1; i <= 10; i++) {
													
      out.write("\r\n");
      out.write("													<div class=\"divTableRow\">\r\n");
      out.write("														<div class=\"divTableCell\" id=\"purchase_ch\"\r\n");
      out.write("															name=\"purchase_ch\">\r\n");
      out.write("															<input type=\"checkbox\">\r\n");
      out.write("														</div>\r\n");
      out.write("														<div class=\"divTableCell\" id=\"purchase_no\"\r\n");
      out.write("															name=\"purchase_no\">");
      out.print(i);
      out.write("</div>\r\n");
      out.write("														<div class=\"divTableCell\" id=\"purchase_date\"\r\n");
      out.write("															name=\"purchase_date\">\r\n");
      out.write("															<input type=\"date\">\r\n");
      out.write("														</div>\r\n");
      out.write("														<div class=\"divTableCell\" id=\"purchase_item\"\r\n");
      out.write("															name=\"purchase_item\">\r\n");
      out.write("															<input type=\"text\">\r\n");
      out.write("														</div>\r\n");
      out.write("														<div class=\"divTableCell\" id=\"purchase_price\"\r\n");
      out.write("															name=\"purchase_price\">\r\n");
      out.write("															<input type=\"text\">\r\n");
      out.write("														</div>\r\n");
      out.write("														<div class=\"divTableCell\" id=\"purchase_quantity\"\r\n");
      out.write("															name=\"purchase_quantity\">\r\n");
      out.write("															<input type=\"text\">\r\n");
      out.write("														</div>\r\n");
      out.write("														<div class=\"divTableCell\" id=\"purchase_kind\"\r\n");
      out.write("															name=\"purchase_kind\">\r\n");
      out.write("															<select>\r\n");
      out.write("																<option>카드</option>\r\n");
      out.write("																<option>현금</option>\r\n");
      out.write("																<option>배달앱</option>\r\n");
      out.write("															</select>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("\r\n");
      out.write("													");

													}
													
      out.write("\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"divTableFoot tableFootStyle\">\r\n");
      out.write("													<div class=\"divTableRow\">\r\n");
      out.write("														<div class=\"divTableCell\">foot1</div>\r\n");
      out.write("														<div class=\"divTableCell\">foot2</div>\r\n");
      out.write("														<div class=\"divTableCell\">foot3</div>\r\n");
      out.write("														<div class=\"divTableCell\">foot4</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- #/ container -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--**********************************\r\n");
      out.write("            Content body end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--**********************************\r\n");
      out.write("            Footer start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("		<div class=\"footer\">\r\n");
      out.write("			<div class=\"copyright\">\r\n");
      out.write("				<p>\r\n");
      out.write("					Copyright &copy; Designed & Developed by <a\r\n");
      out.write("						href=\"https://themeforest.net/user/quixlab\">Quixlab</a> 2018\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--**********************************\r\n");
      out.write("            Footer end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--**********************************\r\n");
      out.write("        Main wrapper end\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("\r\n");
      out.write("	<!--**********************************\r\n");
      out.write("        Scripts\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("	<script src=\"../resource/plugins/common/common.min.js\"></script>\r\n");
      out.write("	<script src=\"../resource/js/custom.min.js\"></script>\r\n");
      out.write("	<script src=\"../resource/js/settings.js\"></script>\r\n");
      out.write("	<script src=\"../resource/js/gleek.js\"></script>\r\n");
      out.write("	<script src=\"../resource/js/styleSwitcher.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Chartjs -->\r\n");
      out.write("	<script src=\"../resource/plugins/chart.js/Chart.bundle.min.js\"></script>\r\n");
      out.write("	<!-- Circle progress -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"../resource/plugins/circle-progress/circle-progress.min.js\"></script>\r\n");
      out.write("	<!-- Datamap -->\r\n");
      out.write("	<script src=\"../resource/plugins/d3v3/index.js\"></script>\r\n");
      out.write("	<script src=\"../resource/plugins/topojson/topojson.min.js\"></script>\r\n");
      out.write("	<script src=\"../resource/plugins/datamaps/datamaps.world.min.js\"></script>\r\n");
      out.write("	<!-- Morrisjs -->\r\n");
      out.write("	<script src=\"../resource/plugins/raphael/raphael.min.js\"></script>\r\n");
      out.write("	<script src=\"../resource/plugins/morris/morris.min.js\"></script>\r\n");
      out.write("	<!-- Pignose Calender -->\r\n");
      out.write("	<script src=\"../resource/plugins/moment/moment.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"../resource/plugins/pg-calendar/js/pignose.calendar.min.js\"></script>\r\n");
      out.write("	<!-- ChartistJS -->\r\n");
      out.write("	<script src=\"../resource/plugins/chartist/js/chartist.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"../resource/plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js\"></script>\r\n");
      out.write("	<script src=\"../resource/js/dashboard/dashboard-1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("    //요소에서 값을 추출하여 배열로 리턴하는 함수\r\n");
      out.write("    function makeArray(){\r\n");
      out.write("        let arr = new Array();\r\n");
      out.write("        let preProcess = $(\".makeArrayElem\").each((index, val) =>{\r\n");
      out.write("            arr.push($(val).val());\r\n");
      out.write("        });\r\n");
      out.write("        return arr;\r\n");
      out.write("    }\r\n");
      out.write("    // 버튼 누를 시 비동기로 백단으로 보내는 로직\r\n");
      out.write("    $(\"#UpdateDailyInfo\").on(\"click\", ()=>{\r\n");
      out.write("        console.log(\"업데이트 진입\");\r\n");
      out.write("        let array = new Array();\r\n");
      out.write("        array = makeArray();\r\n");
      out.write("        console.log(array);\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url : '/main/Daily_UPDATEProc.do',\r\n");
      out.write("            type : 'post',\r\n");
      out.write("            data : {\r\n");
      out.write("            		\"arr\" : array,\r\n");
      out.write("            },\r\n");
      out.write("            success : result => {\r\n");
      out.write("                if(result === 1){\r\n");
      out.write("                    alert(\"데이터전송 성공\");\r\n");
      out.write("                } else{\r\n");
      out.write("                    alert(\"데이터전송 실패\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("//행 추가 버튼 클릭시 행추가\r\n");
      out.write("$(\"#addRow\").on(\"click\", ()=>{\r\n");
      out.write("	let row0= document.getElementById(\"sal_body\").innerHTML;	\r\n");
      out.write("	let arry = new Array();\r\n");
      out.write("	arry = row0.split(',');\r\n");
      out.write("	console.log(arry[0]);\r\n");
      out.write("	\r\n");
      out.write("	$(\"#sal_body\").append(arry[0]);	\r\n");
      out.write("});\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
